### ISSUE TITLE
Query: do you know if this works with the Arduino setup on Mac OS?

### ISSUE THREAD

**Issue by schnoberts1** [a9183756-gh/Arduino-CMake-Toolchain#65]
It didn't work out of the box for me, but I expect this is an error between chair and keyboard. However, if this hasn't been tested on Mac OS then I'll have a look at the cmake code as well.

My cmake commands was:
```
cmake -DARDUINO_BOARD=mbed_giga.giga  -DCMAKE_MAKE_PROGRAM=make -D ARDUINO_INSTALL_PATH=/opt/homebrew/bin -D CMAKE_TOOLCHAIN_FILE=$AR_CMAKE/Arduino-toolchain.cmake $AR_CMAKE/Examples/04_multi_app
```

I also tried `/Applications/Arduino\ IDE.app` as the install path.

As far as I can tell the search_paths in the library index is fine, but the find library function has an empty search path.

**Comment by KSDaemon** [comment]
Just a quick remark — it works on Mac OS, believe me :)

**Comment by KSDaemon** [comment]
@schnoberts1 And please try one of the more updated forks:
* https://github.com/KSDaemon/Arduino-CMake-Toolchain
* https://github.com/technyon/Arduino-CMake-Toolchain

**Comment by schnoberts1** [comment]
Thanks for the redirect :)

**Comment by schnoberts1** [comment]
... for the record, I found the issue that prevented the examples working. On my selected platform (Giga R1) the Wire library associated with giga-mbed 4.10.0 does not have a library.properties file so the CMake solution skips over them and then the Wire dependent examples fail to build. In fact there's a few "libraries" with this issue despite them being in the GitHub source.
